### ISSUE TITLE
SharedDirectory's header blob re-used for a SharedMap

### ISSUE THREAD

**Issue by agarwal-navin** [microsoft/FluidFramework#5224]
As per [this IcM incident](https://portal.microsofticm.com/imp/v3/incidents/details/228167898/home), we see that the "header" blob of a SharedDirectory is being used for a SharedMap.
Initial analysis points to this being a bug in the driver. More details in [the IcM ticket](https://portal.microsofticm.com/imp/v3/incidents/details/228167898/home).

**Comment by anthony-murphy** [comment]
related #5346

**Comment by markfields** [comment]
@anthony-murphy we can remove the OCE tag since the related incidents were mitigated by disabling blob deduping, right?

**Comment by ChumpChief** [comment]
Removing OCE tag per note this was mitigated already.

**Comment by tylerbutler** [comment]
@jatgarg Can you verify that this is resolved and then close this bug? Thanks!

**Comment by anthony-murphy** [comment]
This but and #5353 are not resolved, but we have turned off the feature. We either need to intestigate further, or just remove the offending feature to close

**Comment by vladsud** [comment]
I want to propose we move it out to May.
Mitigations are in (including disabling code in driver).
We need to get back to it and make a call on what to do next, but I feel like the call would be - not use deduping at all for time being, especially that it's efficiency would be close to zero with blob aggregation.
We have a lot of other work this month (really - last month before GA).

**Comment by jatgarg** [comment]
We already have an issue open for that: https://github.com/microsoft/FluidFramework/issues/5444
Maybe we can close this issue as we are not facing this anymore due to disabling blob deduping. @vladsud

**Comment by jatgarg** [comment]
Closing this issue as we not seeing any new instances for this.
